/* tslint:disable */
/* eslint-disable */
export function __wbg_grapevinewasmartifacts_free(a: number, b: number): void;
export function grapevinewasmartifacts_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function grapevinewasmartifacts_params(a: number, b: number): void;
export function grapevinewasmartifacts_r1cs_url(a: number, b: number): void;
export function grapevinewasmartifacts_wasm_url(a: number, b: number): void;
export function identity_proof(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function degree_proof(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): number;
export function verify_grapevine_proof(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function bincode_create_user_request(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function bincode_degree_proof_request(a: number, b: number, c: number, d: number, e: number): number;
export function bincode_new_relationship_request(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): number;
export function bincode_emit_nullifier_request(a: number, b: number, c: number, d: number): number;
export function __wbg_wbg_rayon_poolbuilder_free(a: number, b: number): void;
export function wbg_rayon_poolbuilder_numThreads(a: number): number;
export function wbg_rayon_poolbuilder_receiver(a: number): number;
export function wbg_rayon_poolbuilder_build(a: number): void;
export function initThreadPool(a: number): number;
export function wbg_rayon_start_worker(a: number): void;
export function read_file(a: number, b: number): number;
export function generate_witness_browser(a: number, b: number, c: number, d: number): number;
export const memory: WebAssembly.Memory;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_3: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb49cb808e4b64cd1(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h8d4df63bb4d69126(a: number, b: number, c: number, d: number): void;
export function __wbindgen_thread_destroy(a: number, b: number, c: number): void;
export function __wbindgen_start(a: number): void;
